spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/tracking_order



logging:
  level:
    com:
      example:
        trackingorder: DEBUG
    org:
      springframework:
        security: DEBUG
      hibernate:
        SQL: DEBUG
